# Generated by Django 2.2.9 on 2019-12-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='pair_name',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='pairs_info',
        ),
    ]
